version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/backup
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=api_vacunas
      - POSTGRES_DB=api_vacunas

